server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api
spring:
  profiles:
    active: wfj
  application:
    name: select-lesson
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'selectlesson'
      paths-to-match: '/**'
      packages-to-scan: anda.selectlesson
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
